### ISSUE TITLE
What's the relationship between mean and p(y|x)? Also std and p(y)

### ISSUE THREAD

**Issue by Juliazy** [hvy/chainer-inception-score#3]
Hello! 
I am implementing inception score and I have two scalar as result, one is score mean and one is score std. I am confused that what is the relationship between the two scalars and p(y|x) and p(y), which evaluates the quality and diversity of generated images. 

Thank you!

**Comment by hvy** [comment]
Hi,
You need many samples from the generator in order to compute a reliable Inception score. Hence the mean and the std. As for the relationship between the score and p(y|x), p(y) I suggest you take a look at the definition in the [paper](https://arxiv.org/pdf/1606.03498.pdf). There are many follow ups on the Inception score as well, such as https://arxiv.org/pdf/1801.01973.pdf.

**Comment by Juliazy** [comment]
Hello Hiroyuki!
Thank you very much for your quick reply! I am a beginner in GAN and computer vision, I really appreciate your detailed explanation!

**Comment by hvy** [comment]
Great. Let me close this issue for now but feel free to open if things aren't clear.
